### ISSUE TITLE
Fix Coveralls build failure

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/bruker2nifti#32]
After resolving #31 the Coveralls failure needs to be investigated.
@SebastianoF As far as I understand, the problem was related to Coveralls trawling through all the external dependency libraries, which was causing it to fail?

**Comment by dzhoshkun** [comment]
[This line](https://github.com/SebastianoF/bruker2nifti/blob/ff743ed79a1c1cc5e53b81f40ed439fab99a777b/.travis.yml#L19) is important.

**Comment by dzhoshkun** [comment]
@SebastianoF The [`--cover-package bruker2nifti` argument](https://github.com/dzhoshkun/bruker2nifti/blob/803a81eafc65faf417091c840cee54a8103f6d46/.travis.yml#L86) restricts coverage stats to the `bruker2nifti` package only.
But that argument is not enabled in your [`.travis.yml`](https://github.com/SebastianoF/bruker2nifti/blob/ff743ed79a1c1cc5e53b81f40ed439fab99a777b/.travis.yml#L88)

See my coveralls output: https://coveralls.io/github/dzhoshkun/bruker2nifti

**Comment by SebastianoF** [comment]
Hi! Thanks for checking (in the week end counts twice!). 
Yep, flags are to be refactored. They are in this state awaiting for me understand a bit more how to use properly travis-CI + coveralls. Your suggestions provided me good starting points for this direction!

**Comment by SebastianoF** [comment]
Due to the recent discoveries about orientation (see issues #11 and #33), it seems that the user will always need a small amount manual adjustment for the conversion. Therefore a 100% coverage may be more an hindrance than an help.
Increasing the coverage for the core and utils modules can still be done, although if you agree, this repo may keep on surviving without coverall for the moment.
